### ISSUE TITLE
Inserting blocks with no factor mask results in crash

### ISSUE THREAD

**Issue by brettfeltmate** [a-hurst/klibs#4]
When no factor mask is provided, insert_block() sets factors to None and passes that to the trial_generator instead of the dict it was expecting.

**Comment by a-hurst** [comment]
Figuratively just encountered this myself. Should be fixed in the latest commit!

**Comment by jmwmulle** [comment]
Austin—

I'm slowly getting back into klibs, here; rewriting NumpySurface entirely
at the moment (though preserving backwards compatibility for now).

I pushed a branch called "test" that repairs a bug (tested) in the EyeLink
class; when you get a chance you should merge that in to the main branch as
the bug is fatal and pretty easy to trigger. Maybe next month we get
together to talk about how to collaborate, going forward? I still have
never had to manage versions and branches and multiple contributers before,
perhaps you can guide me into that world. :)

j

--
"[A]t every stage of history our concern must be to dismantle those forms
of authority and oppression that survive from an era when they might have
been justified in terms of the need for security or survival or economic
development, but that now contribute to---rather than alleviate---material
and cultural deficit." - Noam Chomsky

**Comment by a-hurst** [comment]
Hi Jon, your fix from the test branch has been added to the main branch, thanks! Looks like you caught a mistake in the PyLink API docs: they say the function returns `None` if no new samples, but looking at the source it's just a blind wrapper of a C function that returns 0 if no new samples.

Next month works for me, though I also have next week mostly off (reading week) if you have any time to spare: my schedule's very open.
